### ISSUE TITLE
AUTHENTICATION AND AUTHORIZATION is hidden

### ISSUE THREAD

**Issue by philipsagala** [praekelt/django-recaptcha#142]
I use django-recaptcha for my fresh project and add this modul on login page Site administration. reCaptcha render smooth but after login Authentication and Authorization page is hidden. So our user cannot create user or group if recaptcha activated.

<img width="627" alt="screen shot 2018-01-12 at 11 36 59" src="https://user-images.githubusercontent.com/16225962/34860110-bfc11b90-f78d-11e7-841e-dab97214c2b6.png">

here is the code 

forms.py
`from django import forms
from captcha.fields import ReCaptchaField

class FormWithCaptcha(forms.Form):
    captcha = ReCaptchaField()
`

admin.py
`from django.contrib.admin.sites import AdminSite
from django.conf import settings

class MyAdminWithReCaptcha(AdminSite):
    login_form = MyAdminLoginForm
    login_template = settings.TEMPLATES_LOGIN

admin.site = MyAdminWithReCaptcha()`

i add captcha on template login.html
`  <div class="form-row">
    {{ form.captcha }}
    {{ form.captcha.errors }}
  </div>`

**Comment by AltusBarry** [comment]
django-recaptcha only adds and validates a reCAPTCHA field on forms.

The issue you are experiencing is very likely caused by a permission issue on the user you are testing with. Or admin templates being overridden incorrectly.

If you do determine that django-recaptcha is the one causing this issue, we would very much appreciate it if you could open a PR to address this issue.
