### ISSUE TITLE
django 1.11 support & pip

### ISSUE THREAD

**Issue by mightyroser** [praekelt/django-recaptcha#182]
According to the documentation (https://github.com/praekelt/django-recaptcha#requirements), django 1.11 is supported.  However when I attempt to add django-recaptcha to to my python install with pip either django gets updated to 2.1.x.  If I try to downgrade django back to 1.11 I get the following error:

> django-recaptcha 2.0.2 has requirement django<2.3,>1.11, but you'll have django 1.11 which is incompatible.

setup.py contains the following dependency:https://github.com/praekelt/django-recaptcha/blob/d09bd708c8d7a0764cfc5fd9bfdb1f623c4df557/setup.py#L19
        
It seems that either the documentation or setup.py is incorrect.  According to https://www.djangoproject.com/download/#supported-versions 1.11 will be supported through April 2020.

**Comment by AltusBarry** [comment]
@mightyroser Hey, sorry to hear you are having issues. Strictly speaking Django 1.11 is supported, just not 1.11/1.11.0 specifically. Due to the requirement being`django>1.11` and not `django>=1.11`

We highly suggest installing the latest version of 1.11 as it contains the latest security fixes and updates. Try installing Django 1.11 using `pip install 'Django<2.0'`. Which will install, at the time of writing Django 1.11.20

**Comment by mightyroser** [comment]
@AltusBarry, thank you very much.  My mistake.  I'll close this.
